local tbl = 
{
	
	{
		ephemeral = true,
		id = 0,
		legend = true,
		name = "Empty Block",
		name2 = "Min 400 GP Start Check",
		normal = true,
		singlecheck = true,
		singleuse = true,
		unspoil = true,
	},
	
	{
		addchain = "1",
		ephemeral = true,
		id = 36,
		legend = true,
		name = "Scrutiny",
		normal = true,
		singlecheck = true,
		singleuse = true,
		startgpgt = 400,
		unspoil = true,
	},
	
	{
		ephemeral = true,
		id = 35,
		legend = true,
		name = "Meticulous Prospector",
		normal = true,
		reqchain = "1",
		singlecheck = true,
		singleuse = true,
		unspoil = true,
	},
	
	{
		ephemeral = true,
		id = 36,
		legend = true,
		name = "Scrutiny",
		normal = true,
		reqchain = "1",
		singlecheck = true,
		singleuse = true,
		unspoil = true,
	},
	
	{
		ephemeral = true,
		id = 35,
		legend = true,
		name = "Meticulous Prospector",
		normal = true,
		reqchain = "1",
		singlecheck = true,
		singleuse = true,
		unspoil = true,
	},
	
	{
		ephemeral = true,
		id = 0,
		legend = true,
		name = "Empty Block",
		name2 = "800 AND Collector's Standard is not active",
		normal = true,
		singlecheck = true,
		singleuse = true,
		unspoil = true,
	},
	
	{
		buffsNot = "2418",
		ephemeral = true,
		id = 33,
		legend = true,
		name = "Scour",
		normal = true,
		raregt = 800,
		reqchain = "1",
		singlecheck = true,
		singleuse = true,
		unspoil = true,
	},
	
	{
		ephemeral = true,
		id = 0,
		legend = true,
		name = "Empty Block",
		name2 = "800 AND Collector's Standard is active",
		normal = true,
		singlecheck = true,
		singleuse = true,
		unspoil = true,
	},
	
	{
		ephemeral = true,
		hasbuffs = "2418",
		id = 35,
		legend = true,
		name = "Meticulous Prospector",
		normal = true,
		raregt = 800,
		reqchain = "1",
		singlecheck = true,
		singleuse = true,
		unspoil = true,
	},
	
	{
		ephemeral = true,
		id = 0,
		legend = true,
		name = "Empty Block",
		name2 = "if Collectability >= 850",
		normal = true,
		singlecheck = true,
		singleuse = true,
		unspoil = true,
	},
	
	{
		ephemeral = true,
		id = 35,
		legend = true,
		name = "Meticulous Prospector",
		normal = true,
		raregt = 850,
		reqchain = "1",
		singlecheck = true,
		singleuse = true,
		unspoil = true,
	},
	
	{
		ephemeral = true,
		id = 0,
		legend = true,
		name = "Empty Block",
		name2 = "< 400 gp rotation",
		normal = true,
		singlecheck = true,
		singleuse = true,
		unspoil = true,
	},
	
	{
		addchain = "2",
		ephemeral = true,
		id = 33,
		legend = true,
		name = "Scour",
		normal = true,
		singlecheck = true,
		singleuse = true,
		startgplt = 399,
		unspoil = true,
	},
	
	{
		ephemeral = true,
		hasbuffs = "2418",
		id = 35,
		legend = true,
		name = "Meticulous Prospector",
		normal = true,
		reqchain = "2",
		singlecheck = true,
		singleuse = true,
		unspoil = true,
	},
	
	{
		ephemeral = true,
		id = 33,
		legend = true,
		name = "Scour",
		normal = true,
		reqchain = "2",
		singlecheck = true,
		singleuse = true,
		unspoil = true,
	},
	
	{
		ephemeral = true,
		hasbuffs = "2418",
		id = 35,
		legend = true,
		name = "Meticulous Prospector",
		normal = true,
		reqchain = "2",
		singlecheck = true,
		singleuse = true,
		skip = true,
		unspoil = true,
	},
	
	{
		ephemeral = true,
		id = 33,
		legend = true,
		name = "Scour",
		normal = true,
		reqchain = "2",
		singlecheck = true,
		singleuse = true,
		skip = true,
		unspoil = true,
	},
}



return tbl